// ------- SoShoLife Trust & Safety Intelligence System ---------

// models/BehaviorSignal.js
// Raw behavioral signals emitted by the browser SDK.
// This is a time-series collection — documents are append-only.
// The nightly vectorBuilder job reads from this and produces BehaviorVector.
// TTL index auto-deletes signals older than 35 days (keeping 30-day window + buffer).
'use strict';

const mongoose = require('mongoose');

const BehaviorSignalSchema = new mongoose.Schema(
  {
    userId: {
      type:  mongoose.Schema.Types.ObjectId,
      ref:   'user',
      required: true,
      index: true,
    },

    signalType: {
      type: String,
      required: true,
      enum: [
        'typing_burst',       // { chars, duration_ms, wpm }
        'mouse_move',         // { distance_px, duration_ms, direction_changes }
        'scroll_event',       // { delta_y, interval_ms_since_last }
        'click_event',        // { interval_ms_since_last, target_type }
        'session_start',      // { ip, userAgent, fpHash, referrer }
        'session_end',        // { duration_ms, page_count }
        'navigation',         // { from_page, to_page, method: 'click'|'back'|'direct' }
        'post_created',       // { interval_ms_since_last_post }
        'referral_sent',      // { interval_ms_since_last_referral }
        'form_interaction',   // { field, focus_duration_ms, correction_count }
      ],
    },

    payload: { type: mongoose.Schema.Types.Mixed, required: true },

    // Client-side timestamp (ms since epoch) — NOT trusted for security,
    // but used for relative interval calculations within a session.
    clientTimestamp: { type: Number },

    // Server-side receipt timestamp — this IS the authoritative timestamp.
    receivedOn: { type: Date, default: Date.now, index: true },

    // Session identifier (UUID generated by browser SDK, not persisted across sessions)
    sessionId: { type: String, index: true },

    // IP at time of signal receipt (from Express req.ip)
    ip: { type: String },
  },
  {
    // No timestamps: true — we use receivedAt explicitly for TTL
    versionKey: false,
  }
);

// TTL: auto-delete signals older than 35 days
BehaviorSignalSchema.index({ receivedAt: 1 }, { expireAfterSeconds: 35 * 24 * 60 * 60 });

// Compound index for the vectorBuilder job query:
// "all signals for userId X after date Y"
BehaviorSignalSchema.index({ userId: 1, receivedAt: -1 });
BehaviorSignalSchema.index({ userId: 1, signalType: 1, receivedAt: -1 });

module.exports = mongoose.model('BehaviorSignal', BehaviorSignalSchema);