// models/BehaviorSignal.js
// Raw behavioral signals emitted by the browser SDK.
// This is a time-series collection — documents are append-only.
// The nightly vectorBuilder job reads from this and produces BehaviorVector.
// TTL index auto-deletes signals older than 35 days (keeping 30-day window + buffer).
//
// FIX: The TTL index and both compound indexes were defined against `receivedAt`
// but the schema field is named `receivedOn`. MongoDB cannot use an index on a
// field that doesn't exist — the TTL job never fired (unbounded collection growth)
// and vectorBuilder queries hit full collection scans instead of using the index.
// All three indexes now correctly reference `receivedOn`.
//
// NOTE: If this collection already exists in production you must drop the stale
// indexes manually before deploying:
//   db.behaviorsignals.dropIndex('receivedAt_1')
//   db.behaviorsignals.dropIndex('userId_1_receivedAt_-1')
//   db.behaviorsignals.dropIndex('userId_1_signalType_1_receivedAt_-1')
// Mongoose will then recreate them with the correct field name on next startup.

'use strict';

const mongoose = require('mongoose');

const BehaviorSignalSchema = new mongoose.Schema(
  {
    userId: {
      type:     mongoose.Schema.Types.ObjectId,
      ref:      'user',
      required: true,
      index:    true,
    },

    signalType: {
      type:     String,
      required: true,
      enum: [
        'typing_burst',     // { chars, duration_ms, wpm }
        'mouse_move',       // { distance_px, duration_ms, direction_changes }
        'scroll_event',     // { delta_y, interval_ms_since_last }
        'click_event',      // { interval_ms_since_last, target_type }
        'session_start',    // { ip, userAgent, fpHash, referrer }
        'session_end',      // { duration_ms, page_count }
        'navigation',       // { from_page, to_page, method: 'click'|'back'|'direct' }
        'post_created',     // { interval_ms_since_last_post }
        'referral_sent',    // { interval_ms_since_last_referral }
        'form_interaction', // { field, focus_duration_ms, correction_count }
      ],
    },

    payload: { type: mongoose.Schema.Types.Mixed, required: true },

    // Client-side timestamp (ms since epoch) — NOT trusted for security,
    // but used for relative interval calculations within a session.
    clientTimestamp: { type: Number },

    // Server-side receipt timestamp — this IS the authoritative timestamp.
    // FIX: field name is `receivedOn` — all indexes below must match this name.
    receivedOn: { type: Date, default: Date.now, index: true },

    // Session identifier (UUID generated by browser SDK, not persisted across sessions)
    sessionId: { type: String, index: true },

    // IP at time of signal receipt (from Express req.ip)
    ip: { type: String },
  },
  {
    versionKey: false,
  }
);

// TTL: auto-delete signals older than 35 days.
// FIX: was `{ receivedAt: 1 }` — field does not exist. Corrected to `receivedOn`.
BehaviorSignalSchema.index(
  { receivedOn: 1 },
  { expireAfterSeconds: 35 * 24 * 60 * 60, name: 'ttl_35d' }
);

// Compound indexes for the vectorBuilder job query pattern:
// "all signals for userId X in date window [start, end]"
// FIX: were `receivedAt` — corrected to `receivedOn`.
BehaviorSignalSchema.index({ userId: 1, receivedOn: -1 });
BehaviorSignalSchema.index({ userId: 1, signalType: 1, receivedOn: -1 });

module.exports = mongoose.model('BehaviorSignal', BehaviorSignalSchema);